services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      SPRING_APPLICATION_NAME: emprestimos
      SPRING_JPA_HIBERNATE.DDL_AUTO: update
      SPRING_DATASOURCE_URL: ${URL_BANCO}
      SPRING_DATASOURCE_USERNAME: ${USER_BANCO}
      SPRING_DATASOURCE_PASSWORD: ${PASSWORD_BANCO}
      spring.jpa.properties.hibernate.show_sql: true
      logging.level.org.hibernate.type.descriptor.sql: trace
      logging.level.org.hibernate.orm.jdbc.bind: trace
      org.hibernate.event.internal.DefaultPersistEventListener: true
      org.hibernate.SQL: debug
      org.hibernate.type: trace
      log4j.logger.org.hibernate.transaction: DEBUG
      log4j.logger.org.springframework.transaction: DEBUG
      log4j.logger.org.springframework.transaction.interceptor: trace

    volumes:
      - ./src/main/resources/assets:/assets

    ports:
      - 8083:8080

